Content:
    Salamander:
        root_dir: ${ROOT_DIR}/doc/content
    framework:
        root_dir: ${MOOSE_DIR}/framework/doc/content
    electromagnetics:
        root_dir: ${MOOSE_DIR}/modules/electromagnetics/doc/content
    ray_tracing:
        root_dir: ${MOOSE_DIR}/modules/ray_tracing/doc/content
    modules:
        root_dir: ${MOOSE_DIR}/modules/doc/content
        content:
            - help/development/VSCode.md
            - help/development/analyze_jacobian.md
            - help/finite_element_concepts/nodal_patch_recovery.md
            - application_development/performance_benchmarking.md
            - application_usage/restart_recover.md
    python:
        root_dir: ${MOOSE_DIR}/python/doc/content
        content:
            - python/mms.md
            - python/MooseDocs/**
            - python/moosesqa/index.md
            - python/source/moosetree/Node.md
            - python/testers/**
            - python/CSVDiff.md
            - python/TestHarness.md

Renderer:
    type: MooseDocs.base.MaterializeRenderer
Extensions:
    MooseDocs.extensions.navigation:
        name: SALAMANDER
        repo: https://github.com/idaholab/salamander
        menu:
            Getting Started:
                Installation: getting_started/installation.md
                SALAMANDER on HPC: getting_started/hpc.md
                Using SALAMANDER: getting_started/using_SALAMANDER.md
                User Notes: getting_started/user_notes.md
                Contributing to SALAMANDER: sqa/contributing.md
            Documentation:
                SALAMANDER-only Syntax: syntax/salamander_only.md
                Complete Code Syntax: syntax/index.md
                V&V and Examples: /verification_validation_example/index.md
                Publications using SALAMANDER: publications.md
            Software Quality:
                Software Quality Assurance (SQA) Information: /sqa/index.md
                Code Standards: sqa/salamander_scs.md
            Help:
              SALAMANDER Issues Page: https://github.com/idaholab/SALAMANDER/issues
              SALAMANDER Discussion Forum: https://github.com/idaholab/SALAMANDER/discussions
              MOOSE FAQ page: https://mooseframework.inl.gov/help/faq/index.html
              MOOSE Discussion Forum: https://github.com/idaholab/moose/discussions
    MooseDocs.extensions.appsyntax:
        executable: ${ROOT_DIR}
        remove:
            framework: !include ${MOOSE_DIR}/framework/doc/remove.yml
    MooseDocs.extensions.common:
        shortcuts: !include ${MOOSE_DIR}/framework/doc/globals.yml
    MooseDocs.extensions.acronym:
        acronyms:
            framework: !include ${MOOSE_DIR}/framework/doc/acronyms.yml
            salamander:
                SALAMANDER: Software for Advanced Large-scale Analysis of MAgnetic confinement for Numerical Design, Engineering & Research
                PIC: particle-in-cell
                CFD: computational fluid dynamics
                CAD: computer-aided design
    MooseDocs.extensions.sqa:
        active: true
        categories:
            salamander: !include ${ROOT_DIR}/doc/sqa_salamander.yml
            framework: !include ${MOOSE_DIR}/framework/doc/sqa_framework.yml
            ray_tracing: !include ${MOOSE_DIR}/modules/ray_tracing/doc/sqa_ray_tracing.yml
            electromagnetics: !include ${MOOSE_DIR}/modules/electromagnetics/doc/sqa_electromagnetics.yml
        reports: !include ${ROOT_DIR}/doc/sqa_reports.yml
        repos:
            default: https://github.com/idaholab/salamander
    MooseDocs.extensions.template:
        active: true
