Content:
    Salamander:
        root_dir: ${ROOT_DIR}/doc/content
    framework:
        root_dir: ${MOOSE_DIR}/framework/doc/content
    electromagnetics:
        root_dir: ${MOOSE_DIR}/modules/electromagnetics/doc/content
    ray_tracing:
        root_dir: ${MOOSE_DIR}/modules/ray_tracing/doc/content
    modules:
        root_dir: ${MOOSE_DIR}/modules/doc/content
        content:
            - help/development/VSCode.md
            - help/development/analyze_jacobian.md
            - help/finite_element_concepts/nodal_patch_recovery.md
            - application_development/performance_benchmarking.md
            - application_usage/restart_recover.md
    python:
        root_dir: ${MOOSE_DIR}/python/doc/content
        content:
            - python/mms.md
            - python/MooseDocs/**
            - python/moosesqa/index.md
            - python/source/moosetree/Node.md
            - python/testers/**
            - python/CSVDiff.md
            - python/TestHarness.md

Renderer:
    type: MooseDocs.base.MaterializeRenderer
Extensions:
    MooseDocs.extensions.navigation:
        name: SALAMANDER
        repo: https://github.com/idaholab/salamander
        menu:
            Documentation and Resources:
                Complete Code Manual: syntax/index.md
                Code Standards: sqa/salamander_scs.md
                Contributing to SALAMANDER: /sqa/contributing.md
                Software Quality Assurance (SQA) Information: /sqa/index.md
    MooseDocs.extensions.appsyntax:
        executable: ${ROOT_DIR}
        remove:
            framework: !include ${MOOSE_DIR}/framework/doc/remove.yml
    MooseDocs.extensions.common:
        shortcuts: !include ${MOOSE_DIR}/framework/doc/globals.yml
    MooseDocs.extensions.acronym:
        acronyms:
            framework: !include ${MOOSE_DIR}/framework/doc/acronyms.yml
    MooseDocs.extensions.sqa:
        active: true
        categories:
            salamander: !include ${ROOT_DIR}/doc/sqa_salamander.yml
            framework: !include ${MOOSE_DIR}/framework/doc/sqa_framework.yml
            ray_tracing: !include ${MOOSE_DIR}/modules/ray_tracing/doc/sqa_ray_tracing.yml
            electromagnetics: !include ${MOOSE_DIR}/modules/electromagnetics/doc/sqa_electromagnetics.yml
        reports: !include ${ROOT_DIR}/doc/sqa_reports.yml
        repos:
            default: https://github.com/idaholab/salamander
    MooseDocs.extensions.template:
        active: true
